version: "3.8"

services:
    carthagebox:
        image: tqtezos/flextesa:20200925
        command: ["carthagebox", "start"]
        ports:
            - "20000:20000"
    nats:
        image: nats:latest
        command: []
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
    tzindex:
        image: blockwatch/tzindex
        # https://github.com/blockwatch-cc/tzindex/issues/13
        command: ["sh", "-c", "sleep 10 && tzindex run"]
        ports:
            - "8002:8002"
        environment:
            - TZ_RPC_HOST=carthagebox
            - TZ_RPC_PORT=20000
            - TZ_SERVER_ADDR=0.0.0.0
            - TZ_SERVER_PORT=8002
            - TZ_SERVER_CORS_ENABLE=true
            - TZ_DATABASE_PATH=/data/index
            - TZ_SNAPSHOT_PATH=/data/snapshots
        restart: always
        depends_on:
            - carthagebox
    tzstats:
        image: blockwatch/tzstats
        ports:
            - "8001:8001"
        environment:
            - TZSTATS_API_URL=http://localhost:8002
            - SV_HEADERS_Content-Security-Policy=default-src 'self' 'unsafe-inline' http://localhost:*;
            - SV_SERVER_PORT=8001
        restart: always
        depends_on:
            - tzindex
