version: "3.8"

services:
    carthagebox:
        image: tqtezos/flextesa:20200925
        command: ["carthagebox", "start"]
        ports:
            - "20000:20000"
    nats:
        image: nats:latest
        command: []
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
