#! /usr/bin/env bash

set -euo pipefail

function start() {
    platform rm -f
    platform up
}

function stop() {
    platform down
}

function bootstrap() {
    _import-default-accounts
    tezos-client list known contracts
}

function platform() {
    docker-compose -f docker-compose.yaml "${@:1}"
}

function tezos-client() {
    docker exec -it \
        -e 'TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=yes' \
        $(_get-box-name) \
        tezos-client --endpoint http://localhost:20000 \
        "${@:1}"
}

function tzbox() {
    docker exec -it \
        $(_get-box-name) \
        tzbox \
        "${@:1}"
}

# =======
# private
# =======

function _get-box-name() {
    docker ps --filter "name=tzbox" --format "{{.Names}}"
}

function _import-default-accounts() {
    tezos-client import secret key alice unencrypted:edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq --force
    tezos-client import secret key bob unencrypted:edsk3RFfvaFaxbHx8BMtEW1rKQcPtDML3LXjNqMNLCzC3wLC1bWbAt --force
}

"$@"